[build]
provider = "dotnet"

[phases.build]
cmds = [
    "dotnet restore",
    "dotnet publish -c Release -o ./publish --framework net8.0"
]

[start]
cmd = "dotnet ./publish/CSharpQuizBlazor.dll"

[variables]
DOTNET_VERSION = "8.0"
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"
